I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 28, in script
    e "Hello there, I am Ronnie, Destroyer of KFC."
Exception: Sayer 'e' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 28, in script
    e "Hello there, I am Ronnie, Destroyer of KFC."
  File "C:\Users\kb300310\Downloads\renpy-8.1.3-sdk\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\kb300310\Downloads\renpy-8.1.3-sdk\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'e' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
VissyNovvy 1.0
Tue Nov 14 14:09:47 2023
